package com.flexcodelabs.flextuma.core.entities.whatsapp;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.flexcodelabs.flextuma.core.entities.base.Owner;
import com.flexcodelabs.flextuma.core.helpers.MaskingUtil;
import com.flexcodelabs.flextuma.core.security.EncryptedStringConverter;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "whatsapp_webhook_config", uniqueConstraints = @UniqueConstraint(name = "uk_whatsapp_phone_number_id", columnNames = "phone_number_id"))
@Getter @Setter @NoArgsConstructor @AllArgsConstructor
public class WhatsAppWebhookConfig extends Owner {
    public static final String PLURAL = "whatsappWebhookConfigs";
    public static final String NAME_PLURAL = "WhatsApp Webhook Configurations";
    public static final String NAME_SINGULAR = "WhatsApp Webhook Configuration";
    public static final String ALL = "ALL";
    public static final String READ = ALL, ADD = ALL, DELETE = ALL, UPDATE = ALL;

    @NotBlank
    @Column(name = "phone_number_id", nullable = false)
    private String phoneNumberId;

    @NotBlank
    @Column(name = "callback_url", nullable = false, columnDefinition = "TEXT")
    private String callbackUrl;

    @NotBlank
    @Column(name = "verify_token", nullable = false)
    @jakarta.persistence.Convert(converter = EncryptedStringConverter.class)
    private String verifyToken;

    @JsonIgnore
    @Column(name = "callback_token", nullable = false, unique = true)
    private String callbackToken;

    /** The unique Meta callback URL generated by Flextuma; copy this to WhatsApp Cloud. */
    @Column(name = "meta_callback_url", nullable = false, columnDefinition = "TEXT")
    private String metaCallbackUrl;

    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @Column(name = "signing_secret")
    @jakarta.persistence.Convert(converter = EncryptedStringConverter.class)
    private String signingSecret;

    /** Meta App Secret used to validate X-Hub-Signature-256 on inbound events. */
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @Column(name = "app_secret")
    @jakarta.persistence.Convert(converter = EncryptedStringConverter.class)
    private String appSecret;

    @JsonProperty("signingSecret") public String getMaskedSigningSecret() { return MaskingUtil.mask(signingSecret); }
    @JsonProperty("appSecret") public String getMaskedAppSecret() { return MaskingUtil.mask(appSecret); }
}
